name: Test Build on macOS
on:
  pull_request:
    branches: [master, development]
  push:
    branches: [master, development]

jobs:
  check:
    name: Build GUI on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      
      - name: Install Python Dependencies
        run: pip install -r release_script/requirements.txt
      
      - name: Download and Unzip Processing
        run: |
          curl -O -L --insecure https://github.com/processing/processing4/releases/download/processing-1292-4.2/processing-4.2-macos-x64.zip
          unzip processing-4.2-macos-x64.zip
          ls

      - name: Move Processing.app to Applications
        run: |
          mv Processing.app /Applications/Processing.app

      - name: Add Processing to PATH
        run: |
          echo "$GITHUB_WORKSPACE/release_script/mac_only/" >> $GITHUB_PATH
          chmod +x $GITHUB_WORKSPACE/release_script/mac_only/processing-java
      
      - name: Check PATH
        run: echo $PATH

      - name: Check GITHUB PATH
        run: echo $GITHUB_PATH

      - name: Test processing-java command
        run: |
          processing-java --help

      - name: Copy libraries to Processing
        run: |
          mkdir -p $HOME/Documents/Processing/libraries/
          cp -a $GITHUB_WORKSPACE/OpenBCI_GUI/libraries/. $HOME/Documents/Processing/libraries/

      - name: Run Unit Tests
        run: |
          ls
          python $GITHUB_WORKSPACE/OpenBCI_GUI_UnitTests/run-unittests.py
      
      - name: Build GUI
        run: |
          mkdir $GITHUB_WORKSPACE/temp
          touch temp/timestamp.txt
          touch temp/versionstring.txt
          python $GITHUB_WORKSPACE/release_script/make-release.py --no-prompts
          GUI_COMMIT_TIME=`cat temp/timestamp.txt`
          GUI_VERSION_STRING=`cat temp/versionstring.txt`
